ahand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

 # Effort controller----------------------------------
 # Finger 1
  j1_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 1.0}
  j2_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof1_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}
  j3_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof2_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}
  j4_f1:
    type: effort_controllers/JointPositionController
    joint: f1_dof3_joint
    pid: {p: 10.0, i: 0.001, d: 2.0}

 # Finger 2
  j1_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_f2:
    type: effort_controllers/JointPositionController
    joint: f2_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}


 # Finger 3
  j1_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_f3:
    type: effort_controllers/JointPositionController
    joint: f3_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}

# Thumb
  j1_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof0_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j2_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof1_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j3_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof2_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}
  j4_th:
    type: effort_controllers/JointPositionController
    joint: thumb_dof3_joint
    pid: {p: 100.0, i: 0.001, d: 10.0}


  # Task Inverse Kinematics
  TaskInverseKinematics: 
    type: allegro_hand_controllers/TaskInverseKinematics
    root_name: f1_dof0_link
    tip_name:  f1_dof3_link
    pid_f1_dof1_joint: {p: 1,  i: 0.0, d: 0, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_f1_dof2_joint: {p: 1,  i: 0.0, d: 0, i_clamp_min: -0.3, i_clamp_max: 0.3}
    pid_f1_dof3_joint: {p: 1,  i: 0.0, d: 0, i_clamp_min: -0.3, i_clamp_max: 0.3}

