ahand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: ahand_controllers/AhandJointStateController
    publish_rate: 100

  # Task Inverse Kinematics
  pd_controller:
    type: ahand_controllers/PDController
    publish_rate: 100
