ahand:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: ahand_controllers/AhandJointStateController
    publish_rate: 100

  # PD controller
  pd_controller:
    type: ahand_controllers/PDController
    publish_rate: 300
