ahand:
  # Publish all joint states -----------------------------------
  state_publisher:
    type: ahand_controllers/StatePublisher
    publish_rate: 300

  # PD controller
  pd_controller:
    type: ahand_controllers/PDController
    publish_rate: 300

  empty_controller:
    type: ahand_controllers/EmptyController
    publish_rate: 300