ahand:
  # Publish all joint states -----------------------------------
  state_publisher:
    type: ahand_controllers/StatePublisher
    publish_rate: 330

  ros_controller:
    type: ahand_controllers/ROSController
    publish_rate: 330