<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="allegro_hand_right">

    <xacro:property name="DEG2RAD" value="0.01745329251"/>

    <!-- ======================== BASE PARAMS ========================= -->
    <xacro:property name="palm_link_z" value="0.095"/>

    <!-- ======================== FINGER PARAMS ======================== -->
    <xacro:property name="links_x" value="0.0196"/>
    <xacro:property name="links_y" value="0.0275"/>
    <xacro:property name="link0_z" value="0.0164"/>
    <xacro:property name="link1_z" value="0.0540"/>
    <xacro:property name="link2_z" value="0.0384"/>

    <!-- according to http://wiki.wonikrobotics.com/AllegroHandWiki/index.php/Link_Masses -->
    <xacro:property name="mass_scale" value="1.0"/>
    <xacro:property name="link_0_mass" value="${11.0*0.001*mass_scale}"/>
    <xacro:property name="link_1_mass" value="${65*0.001*mass_scale}"/>
    <xacro:property name="link_2_mass" value="${35.5*0.001*mass_scale}"/>
    <xacro:property name="link_3_mass" value="${9.6*0.001*mass_scale}"/>
    <xacro:property name="link_tip_mass" value="${16.8*0.001*mass_scale}"/>

    <xacro:property name="thumb_0_mass" value="${17.6*0.001*mass_scale}"/>
    <xacro:property name="thumb_1_mass" value="${11.9*0.001*mass_scale}"/>
    <xacro:property name="thumb_2_mass" value="${38.0*0.001*mass_scale}"/>
    <xacro:property name="thumb_3_mass" value="${38.8*0.001*mass_scale}"/>
    <xacro:property name="thumb_tip_mass" value="${16.8*0.001*mass_scale}"/>

    <xacro:property name="palm_mass" value="${415.4*0.001}"/>

    <!-- http://wiki.wonikrobotics.com/AllegroHandWiki/index.php/Joint_Dimensions_and_Directions -->



    <!-- full height from joint to tip. when used,
         the radius of the finger tip sphere will be subtracted
         and one fixed link will be added for the tip. -->
    <xacro:property name="link3_z" value="0.0387"/>
    <xacro:property name="fingerTip_r" value="0.0120"/>
    <xacro:property name="offset_origin_x_const" value="0"/>
    <xacro:property name="offset_origin_y_const" value="0.0435"/>
    <xacro:property name="offset_origin_z_const" value="-0.001542"/>
    <xacro:property name="offset_origin_z_mid_const" value="0.0007"/>

    <!-- ========================= THUMB PARAMS ========================= -->
    <xacro:property name="link0_t_x" value="0.0358"/>
    <xacro:property name="link0_t_y" value="0.0340"/>
    <xacro:property name="link0_t_z" value="0.0455"/>
    <xacro:property name="link1_t_z" value="0.0177"/>
    <xacro:property name="link2_t_z" value="0.0514"/>
    <xacro:property name="link3_t_z" value="0.0543"/>

    <!-- ========================= LIMITS ========================= -->
    <xacro:property name="joint_safety_margin" value="0.0"/>

    <!-- finger limit -->

    <xacro:property name="limit_0_up" value="0.57"/>
    <xacro:property name="limit_0_low" value="-0.57"/>

    <xacro:property name="limit_1_up" value="1.74"/>
    <xacro:property name="limit_1_low" value="-0.296"/>

    <xacro:property name="limit_2_up" value="1.74"/> <!-- 1.809 -->
    <xacro:property name="limit_2_low" value="-0.28"/>

    <xacro:property name="limit_3_up" value="1.73"/>
    <xacro:property name="limit_3_low" value=" -0.28"/>

    <!-- thumb limit -->

    <xacro:property name="limit_0_t_up" value="1.57"/>
    <xacro:property name="limit_0_t_low" value="0.275"/>

    <xacro:property name="limit_1_t_up" value="1.263"/>
    <xacro:property name="limit_1_t_low" value="-0.205"/>

    <xacro:property name="limit_2_t_up" value="1.744"/>
    <xacro:property name="limit_2_t_low" value="-0.289"/>

    <xacro:property name="limit_3_t_up" value="1.819"/>
    <xacro:property name="limit_3_t_low" value="-0.262"/>

    <!-- ============================================================================= -->

  <xacro:include filename="$(find ahand_description)/urdf/common.xacro"/>
  <xacro:property name="b" value="0.2"/>
  <xacro:property name="c" value="0.0"/>


  <!-- Include transmissions -->
  <xacro:include filename="$(find ahand_description)/urdf/ahand_transmission.xacro"/>

  <!-- Include Gazebo -->
  <xacro:include filename="$(find ahand_description)/urdf/ahand_gazebo.xacro"/>


  <!-- URDF model with default base_link (world)-->
  <xacro:macro name="ahand_robot" params="name parent_link xyz rpy">


    <joint name="${name}_base_joint" type="fixed">
      <parent link="${parent_link}"/>
      <child link="${name}_palm_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <!-- PALM -->
    <link name="${name}_palm_link">
      <inertial>
        <origin xyz="0 0 -${palm_link_z/2}" rpy="0 0 0"/>
        <mass value="1.1644" />
        <xacro:cuboid_inertia_def width="0.04" height="0.095" length="0.10" mass="1.1644"/>
      </inertial>
      <visual>
        <geometry>
          <mesh filename="package://ahand_description/meshes/base_link.dae"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0 "/>
          <material name="black">
            <color rgba="0.2 0.2 0.2 1"/>
        </material>
        </visual>
    </link>

    <!-- ============================================================================= -->
    <!-- FINGERS -->
    <!-- RIGHT HAND due to which finger is number 0 -->
    <!-- for LEFT HAND switch the sign of the **offset_origin_y** and **finger_angle_r** parameters-->
    <xacro:finger
	    name="${name}"
            finger_num="0"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="-${5.0*DEG2RAD}"
            />
    <xacro:finger
	    name="${name}"
            finger_num="1"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="0"
            offset_origin_z="${offset_origin_z_mid_const}"
            finger_angle_r="0.0"
            />
    <xacro:finger
	    name="${name}"
            finger_num="2"
            offset_origin_x="${offset_origin_x_const}"
            offset_origin_y="-${offset_origin_y_const}"
            offset_origin_z="${offset_origin_z_const}"
            finger_angle_r="${5.0*DEG2RAD}"
            />
    <!-- THUMB -->
    <xacro:thumb_right
	    name="${name}"
            finger_num="3"
            offset_origin_x="-0.0182"
            offset_origin_y="0.019333"
            offset_origin_z="-0.045987"
            finger_angle_r="0"
            finger_angle_p="-${95*DEG2RAD}"
            finger_angle_y="-${90*DEG2RAD}"
            />
      <!--finger_angle_p="-${95*DEG2RAD}"
      finger_angle_y="-${90*DEG2RAD}"-->



    <!-- ============================================================================= -->

    <xacro:ahand_gazebo name="${name}"/>
    <xacro:ahand_transmission name="${name}"/>

   </xacro:macro>

    <!-- THUMB MACRO -->
   <xacro:macro name="thumb_right" params="name finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r finger_angle_p finger_angle_y">

        <!-- [LINK 12] -->
        <link name="${name}_link_${finger_num*4+0}">
            <inertial>
              <origin xyz="${-link0_t_x/2} 0 0"/>
              <xacro:cuboid_inertia_def width="0.02" height="0.04" length="0.04" mass="${thumb_0_mass}"/>
              <mass value="${thumb_0_mass}" />
            </inertial>
            <visual>
              <geometry>
                <mesh filename="package://ahand_description/meshes/link_12_right.dae"/>
              </geometry>
              <material name="black">
                <color rgba=".2 .2 .2 1"/>
              </material>
              <origin rpy="${180*DEG2RAD} 0 0" xyz="0 0 0"/>
            </visual>
        </link>

        <joint name="${name}_joint_${finger_num*4+0}" type="revolute">
            <axis xyz="-1 0 0"/>
            <limit effort="15" velocity="7"
                   lower="${limit_0_t_low-joint_safety_margin}"
                   upper="${limit_0_t_up-joint_safety_margin}"/>
            <parent link="${name}_palm_link"/>
            <child link="${name}_link_${finger_num*4+0}"/>
            <origin rpy="${finger_angle_r} ${finger_angle_p} ${finger_angle_y}"
                    xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 13] -->
        <link name="${name}_link_${finger_num*4+1}">

          <inertial>
            <origin xyz="0.0 0.0 ${link1_t_z/2} "/>
            <xacro:cuboid_inertia_def width="0.02" height="0.02" length="0.02" mass="${thumb_1_mass}"/>
            <mass value="${thumb_1_mass}" />
          </inertial>

          <visual>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_13.dae"/>
                </geometry>
                <material name="black">
                    <color rgba=".2 .2 .2 1"/>
                </material>
            </visual>
        </link>

        <joint name="${name}_joint_${finger_num*4+1}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_1_t_low+joint_safety_margin}"
                   upper="${limit_1_t_up-joint_safety_margin}"/>
            <parent link="${name}_link_${finger_num*4+0}"/>
            <child link="${name}_link_${finger_num*4+1}"/>
            <origin xyz="-0.027 0.005 0.0399"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 14] -->
        <link name="${name}_link_${finger_num*4+2}">
            <inertial>
                  <origin xyz="${link2_t_z/2} 0.0 0.0"/>
                        <xacro:cuboid_inertia_def width="0.02" height="0.02" length="0.02" mass="${thumb_2_mass}"/>
                  <mass value="${thumb_2_mass}" />
            </inertial>
            <visual>
            	<origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
		<geometry>
                    <mesh filename="package://ahand_description/meshes/link_14.dae"/>
                </geometry>
                <material name="black">
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link2_t_z}"/>
                </geometry>
                <origin rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" xyz="${link2_t_z/2} 0 0"/>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+2}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_2_t_low+joint_safety_margin}"
                   upper="${limit_2_t_up-joint_safety_margin}"/>
            <parent link="${name}_link_${finger_num*4+1}"/>
            <child link="${name}_link_${finger_num*4+2}"/>
            <origin xyz="0 0 ${link1_t_z}" rpy="0 -${90*DEG2RAD} -${90*DEG2RAD}"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 15] -->
        <link name="${name}_link_${finger_num*4+3}">
          <inertial>
                <origin xyz="${link3_t_z/2} 0.0 0.0"/>
                      <xacro:cuboid_inertia_def width="0.02" height="0.02" length="0.02" mass="${thumb_3_mass}"/>
                <mass value="${thumb_3_mass}" />
          </inertial>
          <visual>
            	<origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_15.dae"/>
                </geometry>
                <material name="black">
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link3_t_z-2.0*fingerTip_r}"/>
                </geometry>
                <origin rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" xyz="${(link3_t_z-2.0*fingerTip_r)/2} 0 0"/>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+3}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_3_t_low+joint_safety_margin}"
                   upper="${limit_3_t_up-joint_safety_margin}"/>
            <parent link="${name}_link_${finger_num*4+2}"/>
            <child link="${name}_link_${finger_num*4+3}"/>
            <origin xyz="${link2_t_z} 0 0" rpy="0 0 0"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [FINGER TIP THUMB] -->
        <link name="${name}_link_${finger_num*4+3}_tip">
          <inertial>
                <origin xyz="0.0 0.0 0.0"/>
                      <xacro:cuboid_inertia_def width="0.02" height="0.05" length="0.02" mass="${thumb_tip_mass}"/>
                <mass value="${thumb_tip_mass}" />
          </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_15.0_tip.STL"/>
                </geometry>
                <material name="white">
                    <color rgba=".9 .9 .9 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_15.0_tip.STL"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+3}_tip" type="fixed">
            <parent link="${name}_link_${finger_num*4+3}"/>
            <child link="${name}_link_${finger_num*4+3}_tip"/>
            <origin rpy="0 0 0" xyz="${link3_t_z-fingerTip_r} 0 0"/>
        </joint>
    </xacro:macro>
    <!-- END THUMB MACRO -->

    <!-- THREE FINGER MACRO -->
    <xacro:macro name="finger" params="name finger_num offset_origin_x offset_origin_y offset_origin_z finger_angle_r">

        <!-- [LINK 0, 4, 8] -->
        <link name="${name}_link_${finger_num*4+0}">
            <inertial>
              <origin xyz="0.00 0 0.01"/>
              <xacro:cuboid_inertia_def width="0.025" height="0.02" length="0.025" mass="${link_0_mass}"/>
              <mass value="${link_0_mass}" />
            </inertial>
            <visual>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_0.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link0_z}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${link0_z/2}"/>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+0}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_0_low+joint_safety_margin}"
                   upper="${limit_0_up-joint_safety_margin}"/>
            <parent link="${name}_palm_link"/>
            <child link="${name}_link_${finger_num*4+0}"/>
            <origin rpy="${finger_angle_r} 0 0"
                    xyz="${offset_origin_x} ${offset_origin_y} ${offset_origin_z}"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 1, 5, 9] -->
        <link name="${name}_link_${finger_num*4+1}">
          <inertial>
        	<origin xyz="${link1_z/2} 0. 0." rpy="0 0 1.5707"/>
        	<xacro:cuboid_inertia_def width="0.025" height="0.054" length="0.025" mass="${link_1_mass}"/>
        	<mass value="${link_2_mass}" />
      	  </inertial>
          <visual>
            <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
            <geometry>
              <mesh filename="package://ahand_description/meshes/link_1.dae"/>
            </geometry>
            <material name="black"/>
          </visual>
          <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link1_z}"/>
                </geometry>
                <origin xyz="${link1_z/2} 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
          </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+1}" type="revolute">
            <limit effort="15" velocity="7"
                   lower="${limit_1_low+joint_safety_margin}"
                   upper="${limit_1_up-joint_safety_margin}"/>
            <axis xyz="0 0 1"/>
            <parent link="${name}_link_${finger_num*4+0}"/>
            <child link="${name}_link_${finger_num*4+1}"/>
            <origin rpy="${90*DEG2RAD} -${90*DEG2RAD} 0" xyz="0 0 ${link0_z}"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 2, 6, 10]-->
        <link name="${name}_link_${finger_num*4+2}">
	    <inertial>
              <origin xyz="${link2_z/2} 0 0" rpy="0. 0. 0."/>
              <xacro:cuboid_inertia_def width="0.0384" height="0.025" length="0.025" mass="${link_2_mass}"/>
              <mass value="${link_2_mass}" />
            </inertial>        
    	    <visual>
                <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_2.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link2_z}"/>
                </geometry>
                <origin xyz="${link2_z/2} 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+2}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_2_low+joint_safety_margin}"
                   upper="${limit_2_up-joint_safety_margin}"/>
            <parent link="${name}_link_${finger_num*4+1}"/>
            <child  link="${name}_link_${finger_num*4+2}"/>
            <origin xyz="${link1_z} 0 0"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [LINK 3, 7, 11] -->
        <link name="${name}_link_${finger_num*4+3}">
            <inertial>
              <origin xyz=" 0 0 0" rpy="0. 0. 0."/>
              <xacro:cuboid_inertia_def width="0.02" height="0.025" length="0.025" mass="${link_3_mass}"/>
              <mass value="${link_3_mass}" />
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_3.dae"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${links_x} ${links_y} ${link3_z-2.0*fingerTip_r}"/>
                </geometry>
                <origin xyz="${(link3_z-2.0*fingerTip_r)/2} 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+3}" type="revolute">
            <axis xyz="0 0 1"/>
            <limit effort="15" velocity="7"
                   lower="${limit_3_low+joint_safety_margin}"
                   upper="${limit_3_up-joint_safety_margin}"/>
            <parent link="${name}_link_${finger_num*4+2}"/>
            <child link="${name}_link_${finger_num*4+3}"/>
            <origin xyz="${link2_z} 0 0"/>
            <dynamics damping="${b}" friction="${c}"/>
        </joint>

        <!-- [FINGER TIP] -->
        <link name="${name}_link_${finger_num*4+3}_tip">
            <inertial>
                <origin xyz="0 0 0"/>
                <xacro:cuboid_inertia_def width="0.02" height="0.020" length="0.020" mass="${link_tip_mass}"/>
                <mass value="${link_tip_mass}"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 ${90*DEG2RAD} 0"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_3_tip.STL"/>
                </geometry>
                <material name="white">
                    <color rgba=".9 .9 .9 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}"/>
                <geometry>
                    <mesh filename="package://ahand_description/meshes/link_3_tip.STL"/>
                </geometry>
            </collision>
        </link>

        <joint name="${name}_joint_${finger_num*4+3}_tip" type="fixed">
            <parent link="${name}_link_${finger_num*4+3}"/>
            <child link="${name}_link_${finger_num*4+3}_tip"/>
            <origin rpy="0 0 0" xyz="${link3_z-fingerTip_r} 0 0"/>
        </joint>
    </xacro:macro>
    <!-- [[END]] THREE FINGER MACRO -->


</robot>
